@startuml Sequence Diagram
participant Invoker
participant CommandDoTheDishes
participant Receiver


Invoker -> CommandDoTheDishes : DoTheDishes()
activate Invoker
activate CommandDoTheDishes
CommandDoTheDishes -> Receiver : Execute()
deactivate CommandDoTheDishes
deactivate Receiver


@enduml